services:
  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    container_name: expense-tracker_client
    volumes:
      - ./dist:/var/www/expense-tracker
    command: sh -c "cp -r /app/dist/* /var/www/expense-tracker/ && tail -f /dev/null"
    networks:
      - caddy_net
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker_server
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true