services:
  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    container_name: expense-tracker_client
    volumes:
      - static-files:/app/dist
    command: sh -c "cp -r /app/build/* /app/dist/expense-tracker/ && tail -f /dev/null"
    networks:
      - caddy_net
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker_server
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true

volumes:
  static-files:
    external: true