services:
  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    ports:
      - "5501:8080"
    depends_on:
      - server
    networks:
      - expense-tracker-network

  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - expense-tracker-network


networks:
  expense-tracker-network:
    driver: bridge