name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat << EOF > .env
          NODE_ENV=production
          BASE_URL=${{ vars.BASE_URL }}
          DATABASE_URL=${{ vars.DATABASE_URL }}
          EOF

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_USER: ${{ vars.SERVER_USER }}
        run: |
          # Create the directory if it doesn't exist
          ssh ${SERVER_USER}@${SERVER_IP} "mkdir -p /apps/expense-tracker"

          # Use rsync to copy files
          rsync -avz --delete ./ ${SERVER_USER}@${SERVER_IP}:/apps/expense-tracker/

          # Setup and deploy
          ssh ${SERVER_USER}@${SERVER_IP} << EOF
            set -e  # Exit immediately if a command exits with a non-zero status
            set -x  # Print commands and their arguments as they are executed

            # Update package list
            sudo apt-get update

            # Navigate to the project directory
            cd /apps/expense-tracker

            # Build and start Docker containers
            echo "Starting build process..."
            docker-compose -p expense-tracker up -d --build --remove-orphans
          EOF
